AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  cloud-resume-python

  Sample SAM Template for cloud-resume-python

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

#Resources:    
    
 # MyWebsite:
 #   Type: AWS::S3::Bucket
 #   Properties:
 #     BucketName: al-cloud-resume-challenge

 # DynamoDBTable:
 #   Type: AWS::DynamoDB::Table
 #   Properties:
 #     TableName: cloud-resume-challenge
 #     BillingMode: PAY_PER_REQUEST
 #     AttributeDefinitions:
 #       - AttributeName: "ID"
 #         AttributeType: "S"
 #     KeySchema:
 #       - AttributeName: "ID"
 #         KeyType: "HASH"    

  MyRoute53Record:
    Type: "AWS::Route53::RecordSetGroup"
    Properties:
      HostedZoneId: Z0677754ZBYHU5RPIFKB # TODO: Don't hardcode me
      RecordSets:
        - Name: al-resume.co.uk # TODO: Don't hardcode me
          Type: A
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2
            DNSName: !GetAtt MyDistribution.DomainName  

#  MyCertificate:
#    Type: AWS::CertificateManager::Certificate
#    Properties:
#      DomainName: al-resume.co.uk # TODO: Don't hardcode me
#      ValidationMethod: DNS  

#Creating cloudfront distribution
#  MyDistribution:
#    Type: "AWS::CloudFront::Distribution"
#    Properties:
#      DistributionConfig:
#        ViewerCertificate:
#            AcmCertificateArn: !Ref MyCertificate
#            SslSupportMethod: sni-only
#        Aliases: 
#          - al-resume.co.uk 
#        DefaultCacheBehavior:
#          ViewerProtocolPolicy: allow-all
#          TargetOriginId: al-cloud-resume.s3-website-us-east-1.amazonaws.com
#          DefaultTTL: 0
#          MinTTL: 0
#          MaxTTL: 0
#          ForwardedValues:
#            QueryString: false
#        Origins:
#          - DomainName: al-cloud-resume.s3-website-us-east-1.amazonaws.com
#            Id: al-cloud-resume.s3-website-us-east-1.amazonaws.com
#            CustomOriginConfig:
#              OriginProtocolPolicy: http-only
#        Enabled: "true"
#        DefaultRootObject: index.html


  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get


  GetCountFunction:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
        - DynamoDBCrudPolicy:
            TableName: cloud-resume-challenge
      CodeUri: get-function/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api 
          Properties:
            Path: /get
            Method: get

  PutCountFunction:
    Type: AWS::Serverless::Function 
    Properties:
      Policies:
        - DynamoDBCrudPolicy:
            TableName: cloud-resume-challenge
      CodeUri: put-function/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /put
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
